### ISSUE TITLE
环境安装问题

### ISSUE THREAD

**Issue by dadaplm** [bywlzts/DMFourLLIE#1]
您好，在安装conda create --name DMFourLLIE --file requirements.txt时会报下面错
<img width="698" alt="截屏2024-12-06 10 09 12" src="https://github.com/user-attachments/assets/1dca5d24-c967-4102-9311-9592ade2abc6">
请问这个该怎么解决呢，感谢您在低光图像增强领域的贡献。

**Comment by bywlzts** [comment]
您好，感谢您的关注。 我更新了我当前的conda虚拟环境配置文件environment.yml和说明，您可以参考新的安装引导environment.yml。

**Comment by dadaplm** [comment]
好的，谢谢
