### ISSUE TITLE
指标复现

### ISSUE THREAD

**Issue by JayShao-Xie** [bywlzts/DMFourLLIE#2]
非常感谢您卓越的工作！
但是复现指标与原文报告指标存在较大差距，麻烦您看看以下复现步骤是否存在问题：
1. 按照您提供的[红外图像生成链接](https://github.com/RPM-Robotics-Lab/sRGB-TIR)生成低光照图像的红外图像
`python inference_batch.py --input_folder ../data/LOLv2/Real_captured/train/input --output_folder LOLv2RealTrainfr --checkpoint ./translation_weights.pt --a2b 0 --seed 1234 --num_style 5 --synchronized --output_only --config configs/tir2rgb_folder.yaml`
2. 修改LOLv2_real.yml中train dataroot_FR路径改为步骤1生成的LOLv2RealTrainfr_00
3. val dataroot_FR操作与步骤1、2保持一致
4. 其他配置保持不变

非常感谢您的帮助！

**Comment by bywlzts** [comment]
您好，感谢您的关注。

**Comment by bywlzts** [comment]
您好，我发现LOL-v2-Real数据集上的指标不稳定，上传的代码时在huawei数据集上验证了比论文指标高一些，LOL-v2略低，您可以试着尝试一下第二阶段的通道数，我们是在4090单卡上进行的实验，红外图像取01的，并且可以尝试修改第二阶段的通道数32/64。我这边随后更新一下v2的配置文件，感谢您的关注。

**Comment by JayShao-Xie** [comment]
> 您好，我发现LOL-v2-Real数据集上的指标不稳定，上传的代码时在huawei数据集上验证了比论文指标高一些，LOL-v2略低，您可以试着尝试一下第二阶段的通道数，我们是在4090单卡上进行的实验，红外图像取01的，并且可以尝试修改第二阶段的通道数32/64。我这边随后更新一下v2的配置文件，感谢您的关注。

感谢！我再重新复现一下！
